# Generated by Django 4.2.6 on 2023-10-21 15:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150, verbose_name='Действие')),
                ('time', models.DateTimeField(verbose_name='Время')),
                ('frequency', models.SmallIntegerField(default=7, verbose_name='Периодичность выполнения')),
                ('time_to_complete', models.DurationField(verbose_name='Время выполнения')),
                ('place', models.CharField(max_length=150, verbose_name='Место')),
                ('reward', models.CharField(blank=True, max_length=150, null=True, verbose_name='Вознаграждение')),
                ('is_published', models.BooleanField(default=False, verbose_name='Публичная')),
                ('is_pleasant', models.BooleanField(default=False, verbose_name='Приятная')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
                'ordering': ['time'],
            },
        ),
    ]
